cargo-features = ["strip"]

[package]
name = "advent-of-code-2020"
version = "1.0.0"
authors = ["Max Larsson <maxslarsson@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.4"
lazy_static = "1.4"
num = "0.3"